#
# Copyright (c) 2017-2018 Bitprim Inc.
#
# This file is part of Bitprim.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

branches:
  only:
    - master
    - dev
    - /^v\d+\.\d+\.\d+$/
    - /^release-\d+\.\d+\.\d+$/
    - /^feature-ci-.+$/
    - /^feature_ci_.+$/

build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14

        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        #   CONAN_VISUAL_VERSIONS: 12
 
        # - MINGW_CONFIGURATIONS: "7@x86_64@seh@posix, 6@x86_64@seh@posix, 5@x86_64@seh@posix, 4.9@x86_64@seh@posix"

        - MINGW_CONFIGURATIONS: "8@x86_64@seh@posix"
        - MINGW_CONFIGURATIONS: "7@x86_64@seh@posix"
        - MINGW_CONFIGURATIONS: "6@x86_64@seh@posix"
        - MINGW_CONFIGURATIONS: "5@x86_64@seh@posix"
        # - MINGW_CONFIGURATIONS: "4.9@x86_64@seh@posix"     


init:
  # - echo "*******************************************************"
  # - echo %APPVEYOR_REPO_TAG%
  # - echo %APPVEYOR_REPO_BRANCH%
  # - echo %APPVEYOR_REPO_TAG_NAME%
  # - echo %APPVEYOR_REPO_COMMIT_MESSAGE%
  # - echo "*******************************************************"

  - ps: |
      if ($Env:APPVEYOR_REPO_BRANCH -ceq "master" -And [string]::IsNullOrEmpty($Env:APPVEYOR_REPO_TAG_NAME)) {
        Write-Host "branch is master without tags, exiting"
        Exit-AppveyorBuild
      }

      # Note(fernando): It is implemented natively in Appveyor...
      # if ($Env:APPVEYOR_REPO_COMMIT_MESSAGE -like "*\[skip appveyor\]*") {
      #   Write-Host "[skip appveyor] detected in commit message, exiting"
      #   Exit-AppveyorBuild
      # }

install:
  # - echo "*******************************************************"
  # - echo %APPVEYOR_REPO_TAG%
  # - echo %APPVEYOR_REPO_BRANCH%
  # - echo %APPVEYOR_REPO_TAG_NAME%
  # - echo %APPVEYOR_REPO_COMMIT_MESSAGE%
  # - echo "*******************************************************"

  - set PATH=%PATH%;%PYTHON%/Scripts/

  - pip.exe install conan --upgrade
  # - pip.exe install conan==1.0.0b5   #Fixed Beta version...

  - pip.exe install conan_package_tools
  - pip.exe install cpuid --upgrade
  
  - conan user # It creates the conan data directory

test_script:

  - git submodule init
  # - git submodule update --remote
  - git submodule update
  # - dir *.*

  # - git fetch --unshallow
  # - export BITPRIM_BUILD_NUMBER="$(git describe)"
  - for /f %%i in ('git describe') do set BITPRIM_BUILD_NUMBER=%%i
  - echo %BITPRIM_BUILD_NUMBER%

  # - echo %APPVEYOR_REPO_BRANCH%
  # - dir *.*
  # - cd

  - ps: |
      if ($Env:APPVEYOR_REPO_BRANCH -ceq "dev") {
        $Env:BITPRIM_CONAN_CHANNEL = "testing"
      }
      elseif ($Env:APPVEYOR_REPO_BRANCH.StartsWith("release")) {
        $Env:BITPRIM_CONAN_CHANNEL = "stable"
      }
      elseif ($Env:APPVEYOR_REPO_BRANCH.StartsWith("feature")) {
        $Env:BITPRIM_CONAN_CHANNEL = $Env:APPVEYOR_REPO_BRANCH
      }
      else {
        $Env:BITPRIM_CONAN_CHANNEL = "stable"
      }
      
      # if ([System.IO.File]::Exists("conan_channel")) {
      #   Write-Host "Creating conan_channel file"
      #   $Env:BITPRIM_CONAN_CHANNEL | Out-File conan_channel
      # }

  # - dir *.*
  # - echo %BITPRIM_CONAN_CHANNEL%

  - python build.py
